### ISSUE TITLE
Module still versioned as 3.2.1

### ISSUE THREAD

**Issue by ImportTaste** [hjorslev/SteamPS#54]
3.2.2 is in the releases section as Stable, but in SteamPS.psd1 (and possibly other places) the module is still versioned as 3.2.1.

It also didn't get updated on PowershellGallery.

**Comment by hjorslev** [comment]
Hey @ImportTaste 

I will fix it later tonight. I hid the version on the PSGallery due to a bug in Get-SteamServerInfo that is now fixed in #53 by @ThePoShWolf.
